---
name: Test

on:
  workflow_call:

jobs:
  validate:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: ⏬ Checkout repo
        uses: actions/checkout@v5

      - name: 🔄 Init Cache
        uses: nmerget/npm-cache-action@main

      - name: 👨‍🔬👩‍🔬 Test repo
        run: npm run test
